name: Running tests

on:
    push:
    pull_request:
    schedule:
        -   cron: '* * * * *'

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                laravel: [8.*, 7.*]
                os:
                    - ubuntu-latest
                include:
                    -   laravel: 8.*
                        testbench: 6.*
                        php: 7.3
                        phpunit: 9.3.*

                    -   laravel: 7.*
                        testbench: 5.*
                        php: 7.3
                        phpunit: 8.4.*

        name: ${{ matrix.os }} - L${{ matrix.laravel }} - P${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    ini-values: memory_limit=-1
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "phpunit/phpunit:${{ matrix.phpunit }}" "orchestra/testbench:${{ matrix.testbench }}" monolog/monolog --no-interaction --no-update
                    composer update --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit
